export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

// Save User Data
export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const EDIT_USER_DATA = 'EDIT_USER_DATA';
export const SIGN_OUT_USER = 'SIGN_OUT_USER'
